#!/usr/bin/env python3
"""
scripts/refresh-yt-cookies.py

Reads YouTube + Google cookies from your local Chrome browser,
then uploads them as YOUTUBE_COOKIES GitHub Actions secret.

Usage:
  python scripts/refresh-yt-cookies.py [--repo owner/repo]

Requirements:
  pip install browser-cookie3

Run this whenever the GitHub Actions workflow starts showing
"Sign in to confirm you're not a bot" errors (usually every few months).
"""

import argparse
import base64
import subprocess
import sys
import os

# ── Install browser-cookie3 if missing ────────────────────────────────────────

try:
    import browser_cookie3
except ImportError:
    print("Installing browser-cookie3...")
    # Try with --break-system-packages for Homebrew Python on macOS
    r = subprocess.run(
        [sys.executable, "-m", "pip", "install", "browser-cookie3", "--break-system-packages"],
        capture_output=True, text=True
    )
    if r.returncode != 0:
        # Fallback: user install
        subprocess.run(
            [sys.executable, "-m", "pip", "install", "browser-cookie3", "--user"],
            check=True
        )
    import browser_cookie3

# ── Args ──────────────────────────────────────────────────────────────────────

parser = argparse.ArgumentParser()
parser.add_argument('--repo', default='Jia-Hong-Peng/jolike.com')
args = parser.parse_args()

# ── Extract cookies from Chrome ───────────────────────────────────────────────

DOMAINS = ['.youtube.com', '.google.com', 'youtube.com', 'google.com']

AUTH_COOKIES = {'SID', 'SSID', 'HSID', 'APISID', 'SAPISID',
                '__Secure-1PSID', '__Secure-3PSID', '__Secure-1PAPISID', '__Secure-3PAPISID'}

def try_browser(name, fn):
    try:
        cj = fn(domain_name='.youtube.com')
        cookies = list(cj)
        auth_found = {c.name for c in cookies if c.name in AUTH_COOKIES}
        print(f"  {name}: {len(cookies)} cookies, auth={sorted(auth_found) or 'NONE (not logged in)'}")
        return cookies, auth_found
    except Exception as e:
        print(f"  {name}: unavailable ({e})")
        return [], set()

print("Reading YouTube/Google cookies from browsers...")
print("(You may see a macOS Keychain permission dialog — click Allow)")
print()

browsers = [
    ("Chrome",  browser_cookie3.chrome),
    ("Firefox", browser_cookie3.firefox),
]
try:
    browsers.append(("Safari", browser_cookie3.safari))
except AttributeError:
    pass

best_cookies = []
best_auth = set()
for name, fn in browsers:
    cookies, auth = try_browser(name, fn)
    if len(auth) > len(best_auth):
        best_cookies, best_auth = cookies, auth

if not best_auth:
    print()
    print("⚠️  No authentication cookies found in any browser.")
    print("   Visitor-only cookies may not bypass YouTube bot detection.")
    print("   Make sure you are LOGGED INTO YouTube (youtube.com) in Chrome or Firefox.")
    print("   Continuing anyway — cookies may still help somewhat.")
    print()

cj = best_cookies

# Convert to Netscape cookies.txt format (what yt-dlp accepts)
lines = [
    "# Netscape HTTP Cookie File",
    "# Automatically generated by scripts/refresh-yt-cookies.py",
    "",
]

count = 0
for cookie in cj:
    domain = cookie.domain or ''
    if not any(domain.endswith(d.lstrip('.')) for d in DOMAINS):
        continue
    include_subdomains = "TRUE" if domain.startswith('.') else "FALSE"
    secure = "TRUE" if cookie.secure else "FALSE"
    expires = int(cookie.expires) if cookie.expires else 2147483647
    lines.append(
        f"{domain}\t{include_subdomains}\t{cookie.path}\t{secure}\t{expires}\t{cookie.name}\t{cookie.value}"
    )
    count += 1

if count == 0:
    print("\n❌  No YouTube/Google cookies found in any browser.")
    print("Make sure you are logged into YouTube at https://www.youtube.com")
    sys.exit(1)

cookies_text = "\n".join(lines)
print(f"✓  Extracted {count} cookies")

# ── Upload to GitHub Secret ───────────────────────────────────────────────────

encoded = base64.b64encode(cookies_text.encode()).decode()

print(f"Uploading to GitHub secret YOUTUBE_COOKIES ({args.repo})...")

result = subprocess.run(
    ["gh", "secret", "set", "YOUTUBE_COOKIES",
     "--repo", args.repo,
     "--body", encoded],
    capture_output=True, text=True
)

if result.returncode != 0:
    print(f"\n❌  gh secret set failed:\n{result.stderr}")
    print("Make sure `gh` is installed and authenticated (`gh auth status`)")
    sys.exit(1)

print(f"✅  YOUTUBE_COOKIES updated in {args.repo}")
print()
print("Trigger a test run with:")
print("  gh workflow run fetch-transcripts.yml --field limit=10")
