#!/usr/bin/env python3
"""
scripts/refresh-yt-cookies.py

Reads YouTube + Google cookies from your local Chrome browser,
then uploads them as YOUTUBE_COOKIES GitHub Actions secret.

Usage:
  python scripts/refresh-yt-cookies.py [--repo owner/repo]

Requirements:
  pip install browser-cookie3

Run this whenever the GitHub Actions workflow starts showing
"Sign in to confirm you're not a bot" errors (usually every few months).
"""

import argparse
import base64
import subprocess
import sys
import os

# ── Install browser-cookie3 if missing ────────────────────────────────────────

try:
    import browser_cookie3
except ImportError:
    print("Installing browser-cookie3...")
    # Try with --break-system-packages for Homebrew Python on macOS
    r = subprocess.run(
        [sys.executable, "-m", "pip", "install", "browser-cookie3", "--break-system-packages"],
        capture_output=True, text=True
    )
    if r.returncode != 0:
        # Fallback: user install
        subprocess.run(
            [sys.executable, "-m", "pip", "install", "browser-cookie3", "--user"],
            check=True
        )
    import browser_cookie3

# ── Args ──────────────────────────────────────────────────────────────────────

parser = argparse.ArgumentParser()
parser.add_argument('--repo', default='Jia-Hong-Peng/jolike.com')
args = parser.parse_args()

# ── Extract cookies from Chrome ───────────────────────────────────────────────

DOMAINS = ['.youtube.com', '.google.com', 'youtube.com', 'google.com']

print("Reading YouTube/Google cookies from Chrome...")
print("(Chrome can stay open — this reads a copy of the cookie database)")

try:
    cj = browser_cookie3.chrome(domain_name='.youtube.com')
except Exception as e:
    print(f"\n❌  Failed to read Chrome cookies: {e}")
    print("Make sure:")
    print("  1. Google Chrome is installed")
    print("  2. You are logged into YouTube in Chrome")
    sys.exit(1)

# Convert to Netscape cookies.txt format (what yt-dlp accepts)
lines = [
    "# Netscape HTTP Cookie File",
    "# Automatically generated by scripts/refresh-yt-cookies.py",
    "",
]

count = 0
for cookie in cj:
    domain = cookie.domain or ''
    if not any(domain.endswith(d.lstrip('.')) for d in DOMAINS):
        continue
    include_subdomains = "TRUE" if domain.startswith('.') else "FALSE"
    secure = "TRUE" if cookie.secure else "FALSE"
    expires = int(cookie.expires) if cookie.expires else 2147483647
    lines.append(
        f"{domain}\t{include_subdomains}\t{cookie.path}\t{secure}\t{expires}\t{cookie.name}\t{cookie.value}"
    )
    count += 1

if count == 0:
    print("\n❌  No YouTube/Google cookies found in Chrome.")
    print("Make sure you are logged into YouTube at https://www.youtube.com")
    sys.exit(1)

cookies_text = "\n".join(lines)
print(f"✓  Extracted {count} cookies")

# ── Upload to GitHub Secret ───────────────────────────────────────────────────

encoded = base64.b64encode(cookies_text.encode()).decode()

print(f"Uploading to GitHub secret YOUTUBE_COOKIES ({args.repo})...")

result = subprocess.run(
    ["gh", "secret", "set", "YOUTUBE_COOKIES",
     "--repo", args.repo,
     "--body", encoded],
    capture_output=True, text=True
)

if result.returncode != 0:
    print(f"\n❌  gh secret set failed:\n{result.stderr}")
    print("Make sure `gh` is installed and authenticated (`gh auth status`)")
    sys.exit(1)

print(f"✅  YOUTUBE_COOKIES updated in {args.repo}")
print()
print("Trigger a test run with:")
print("  gh workflow run fetch-transcripts.yml --field limit=10")
